<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Mollie\Subscriptions\Block\Frontend\Customer\Account\ActiveSubscriptions $block */
?>

<?php foreach ($block->getSubscriptions() as $subscription): ?>
    <?=$subscription->getId(); ?> -
    <?=$subscription->getAmount(); ?> -
    <?=$subscription->getStatus(); ?> -
    <?=$subscription->getDescription(); ?>

    <?php if ($subscription->getStatus() == 'active'): ?>
        -
        <a href="<?=$this->getUrl('mollie_subscriptions/index/cancel', ['subscription_id' => $subscription->getId()]); ?>">
            Cancel
        </a>
    <?php endif; ?>
    <br>
<?php endforeach; ?>
