<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Mollie\Subscriptions\Block\Frontend\Customer\Account\ActiveSubscriptions $block */
?>

<?php foreach ($block->getSubscriptions() as $subscription): ?>
    <?php $plan = $subscription->getPlan()->getName() . ' - ' . $subscription->getPlan()->getDescription(); ?>
    Plan: <?= $block->escapeHtml($plan); ?><br>
    Started: <?= $block->escapeHtml($subscription->getStartDate()); ?><br>
    <br>
<?php endforeach; ?>
